# See https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  secret_key: "this should only be used behind VPN"
  limiter: false  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
search:
  formats:
    - html
    - json
